import { useState } from 'react';
import { Link } from 'wouter';
import { ArrowLeft, Check, ChevronRight, Music2 } from 'lucide-react';
import { artistTypes, cities, genres, venueTypes } from '../data/constants';
import type { Artist } from '../types';

const stepTitles = ['Introduce your project', 'What do you sound like?', 'Where should we look?', 'Tell us about your show', 'Add your artist links'];
const stepCopy = ['The basics help us make this feel like your own booking workspace.', 'Pick every sound that genuinely belongs in your set.', 'Set a home base and the cities you would actually consider.', 'Room size and audience context make the fit score more practical.', 'Private links are not required. Add the places where a booker can hear or follow you.'];
const linkNames: Array<[keyof Artist['links'], string]> = [['spotify','Spotify'],['appleMusic','Apple Music'],['youtube','YouTube'],['soundcloud','SoundCloud'],['instagram','Instagram'],['tiktok','TikTok']];
export function Onboarding({ initial, onComplete, recovered = false }: { initial: Artist; onComplete: (artist: Artist) => void; recovered?: boolean }) {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState(initial);
  const [error, setError] = useState('');
  const update = <K extends keyof Artist>(key: K, value: Artist[K]) => setForm((current) => ({ ...current, [key]: value }));
  const flip = (key: 'genres' | 'preferredCities' | 'preferredVenueTypes', value: string) => {
    const current = form[key];
    update(key, (current.includes(value) ? current.filter((item) => item !== value) : [...current, value]) as Artist[typeof key]);
  };
  const chips = (key: 'genres' | 'preferredCities' | 'preferredVenueTypes', values: string[]) => <div className="chip-select">{values.map((value) => <button type="button" className={`chip ${form[key].includes(value) ? 'selected' : ''}`} aria-pressed={form[key].includes(value)} onClick={() => flip(key, value)} key={value} data-testid={`onboarding-${key}-${value.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-')}`}>{form[key].includes(value) && <Check size={12} />}{value}</button>)}</div>;
  const numericField = (label: string, key: 'monthlyListeners' | 'socialFollowers') => <div className="form-group"><label htmlFor={`onboard-${key}`}>{label}</label><input id={`onboard-${key}`} className="field" type="number" min="0" value={form[key]} onChange={(event) => update(key, Number(event.target.value))} /></div>;
  return <main className="onboarding-screen"><aside className="onboarding-aside"><div><Link href="/" className="brand"><span className="brand-mark"><Music2 size={18} /></span>getgigs</Link><div style={{ marginTop: '16vh' }}><div className="eyebrow">Less scrolling. Better rooms.</div><h1>Find the stages that feel like yours.</h1><p>We turn venue research into a shortlist that fits your sound, your audience and where you are right now.</p></div></div><div style={{ fontSize: 12, color: '#718477' }}>Built for independent artists, one room at a time.</div></aside>
    <section className="onboarding-main" aria-labelledby="onboarding-title"><div style={{ maxWidth: 560, width: '100%', margin: 'auto' }}>{recovered && <div className="notice" role="status" style={{ marginBottom: 16 }}>Some saved browser data could not be read, so GetGigs restored a safe starting profile. You can update any details below.</div>}<div className="eyebrow">Artist setup · step {step + 1} of 5</div><div className="step-progress" aria-label={`Step ${step + 1} of 5`}>{stepTitles.map((title, index) => <span key={title} className={index <= step ? 'done' : ''} />)}</div><h2 className="onboard-title" id="onboarding-title">{stepTitles[step]}</h2><p className="onboard-sub">{stepCopy[step]}</p>{error && <div className="notice" role="alert">{error}</div>}
      {step === 0 && <div className="form-grid"><div className="form-group"><label htmlFor="onboard-name">Artist / project name</label><input id="onboard-name" className="field" autoFocus value={form.name} onChange={(event) => update('name', event.target.value)} data-testid="input-onboard-name" /></div><div className="form-group"><label htmlFor="onboard-type">Artist type</label><select id="onboard-type" className="select" value={form.artistType} onChange={(event) => update('artistType', event.target.value)}>{artistTypes.map((item) => <option key={item}>{item}</option>)}</select></div><div className="form-group"><label htmlFor="onboard-email">Booking email</label><input id="onboard-email" type="email" className="field" value={form.email} onChange={(event) => update('email', event.target.value)} /></div><div className="form-group"><label htmlFor="onboard-stage">Career stage</label><select id="onboard-stage" className="select" value={form.stage} onChange={(event) => update('stage', event.target.value)}>{['Emerging','Growing','Established','Touring'].map((item) => <option key={item}>{item}</option>)}</select></div></div>}
      {step === 1 && <><div className="form-group"><label>Genres — choose all that fit</label>{chips('genres', genres)}</div><p style={{ fontSize: 12, color: '#829087', marginTop: 15 }}>Your selected genres shape nearly a third of each match.</p></>}
      {step === 2 && <><div className="form-grid"><div className="form-group"><label htmlFor="onboard-city">Home city</label><select id="onboard-city" className="select" value={form.city} onChange={(event) => update('city', event.target.value)}>{cities.map((item) => <option key={item}>{item}</option>)}</select></div><div className="form-group"><label htmlFor="onboard-travel">Willingness to travel</label><select id="onboard-travel" className="select" value={form.willingToTravel ? 'Yes' : 'No'} onChange={(event) => update('willingToTravel', event.target.value === 'Yes')}><option>Yes</option><option>No</option></select></div><div className="form-group"><label htmlFor="onboard-miles">Comfortable travel radius</label><select id="onboard-miles" className="select" value={String(form.travelMiles)} onChange={(event) => { const miles = Number(event.target.value); update('travelMiles', miles); update('radius', miles === 0 ? 'Local only' : `${miles} miles`); }}>{[25,50,100,250].map((miles) => <option value={miles} key={miles}>{miles} miles</option>)}</select></div></div><div className="form-group" style={{ marginTop: 18 }}><label>Preferred cities — choose multiple</label>{chips('preferredCities', cities)}</div></>}
      {step === 3 && <><div className="form-grid">{numericField('Monthly listeners', 'monthlyListeners')}{numericField('Social followers', 'socialFollowers')}<div className="form-group"><label htmlFor="onboard-draw">Typical audience size</label><select id="onboard-draw" className="select" value={form.typicalAudienceSize} onChange={(event) => update('typicalAudienceSize', event.target.value)}>{['Under 100','100–250','250–500','500+','Any'].map((item) => <option key={item}>{item}</option>)}</select></div><div className="form-group"><label htmlFor="onboard-capacity">Room capacity range</label><select id="onboard-capacity" className="select" value={form.capacity} onChange={(event) => update('capacity', event.target.value)}>{['Under 150','150–500','500+','Any'].map((item) => <option key={item}>{item}</option>)}</select></div><div className="form-group"><label htmlFor="onboard-style">Preferred performance style</label><select id="onboard-style" className="select" value={form.style} onChange={(event) => update('style', event.target.value)}>{['Full band','Solo / acoustic','Electronic','DJ set','Flexible'].map((item) => <option key={item}>{item}</option>)}</select></div><div className="form-group"><label htmlFor="onboard-audience">Audience description</label><input id="onboard-audience" className="field" value={form.audience} onChange={(event) => update('audience', event.target.value)} /></div></div><div className="form-group" style={{ marginTop: 18 }}><label>Preferred venue types</label>{chips('preferredVenueTypes', venueTypes)}</div></>}
      {step === 4 && <><div className="form-grid">{linkNames.map(([key, label]) => <div className="form-group" key={key}><label htmlFor={`onboard-link-${key}`}>{label}</label><input id={`onboard-link-${key}`} type="url" className="field" placeholder="https://" value={form.links[key]} onChange={(event) => update('links', { ...form.links, [key]: event.target.value })} /></div>)}</div><p style={{ fontSize: 12, color: '#829087', marginTop: 14 }}>You can add or edit these any time from your artist profile.</p></>}
      <div className="onboard-footer">{step > 0 ? <button className="button" onClick={() => { setStep(step - 1); setError(''); }}><ArrowLeft size={15} /> Back</button> : <span />}{step < 4 ? <button className="button primary" onClick={() => { if (step === 0 && !form.name.trim()) { setError('Add an artist name to continue.'); return; } if (step === 1 && !form.genres.length) { setError('Pick at least one genre to make useful matches.'); return; } setError(''); setStep(step + 1); }} data-testid="button-onboarding-next">Continue <ChevronRight size={15} /></button> : <button className="button primary" onClick={() => onComplete(form)} data-testid="button-finish-onboarding">Show my matches <ChevronRight size={15} /></button>}</div>
    </div></section></main>;
}