import { useRef, useState } from "react";
import { ArrowLeft, Eye, ImagePlus, Pencil, Plus, Trash2 } from "lucide-react";
import type { Opportunity, VerificationStatus } from "../../data/opportunities";
import { normalizeOpportunity } from "../../data/opportunities";
import OpportunityDetailScreen from "../opportunities/OpportunityDetailScreen";
import ImageUploader from "../shared/ImageUploader";
import SafeImage from "../shared/SafeImage";

export default function ManageVenuesScreen({ venues, onChange, onClose }: { venues: Opportunity[]; onChange: (venues: Opportunity[]) => void; onClose: () => void }) {
  const [editing, setEditing] = useState<Opportunity | null>(null);
  const [preview, setPreview] = useState<Opportunity | null>(null);

  if (preview) return <OpportunityDetailScreen opportunity={preview} saved={false} accessMode="authenticated" onBack={() => setPreview(null)} onApply={() => undefined} onToggleSaved={() => undefined}/>;
  if (editing) return <VenueForm value={editing} onCancel={() => setEditing(null)} onSave={(venue) => { const exists = venues.some((item) => item.id === venue.id); onChange(exists ? venues.map((item) => item.id === venue.id ? normalizeOpportunity(venue) : item) : [...venues, normalizeOpportunity(venue)]); setEditing(null); }}/ >;

  return <div className="gg-admin-page"><header><button type="button" onClick={onClose}><ArrowLeft size={15}/> Profile</button><div><span className="gg-kicker">Private workspace</span><h1>Manage Venues</h1><p>Add real venue information manually, keep booking contacts private, and preview the artist experience.</p></div><button type="button" className="primary" onClick={() => setEditing(blankVenue())}><Plus size={15}/> Add Venue</button></header>
    <div className="gg-admin-notice"><strong>Prototype venue editor</strong><span>No scraping is used. Enter and verify information manually before publishing.</span></div>
    <section className="gg-admin-list">{venues.map((venue) => <article key={venue.id}><SafeImage src={venue.publicInfo.coverImage} alt={venue.venueName}/><div><span>{venue.publicInfo.venueType} · {venue.publicInfo.city}, {venue.publicInfo.state}</span><h2>{venue.venueName}</h2><p>{venue.opportunityTitle} · {venue.matchScore}% match</p><small>{venue.dataQuality.verificationStatus}{venue.dataQuality.isDemo ? " · Sample/demo" : ""}</small></div><div className="gg-admin-actions"><button type="button" onClick={() => setPreview(venue)}><Eye size={14}/> Preview</button><button type="button" onClick={() => setEditing(structuredClone(venue))}><Pencil size={14}/> Edit</button><button type="button" className="danger" onClick={() => { if (window.confirm(`Delete ${venue.venueName}?`)) onChange(venues.filter((item) => item.id !== venue.id)); }}><Trash2 size={14}/> Delete</button></div></article>)}</section>
  </div>;
}

function VenueForm({ value, onSave, onCancel }: { value: Opportunity; onSave: (venue: Opportunity) => void; onCancel: () => void }) {
  const [venue, setVenue] = useState(value);
  const galleryRef = useRef<HTMLInputElement>(null);
  const [galleryError, setGalleryError] = useState("");
  const updatePublic = (key: keyof Opportunity["publicInfo"], next: string) => setVenue((current) => ({ ...current, publicInfo: { ...current.publicInfo, [key]: next } }));
  const updateBooking = (key: keyof Opportunity["bookingInfo"], next: string) => setVenue((current) => ({ ...current, bookingInfo: { ...current.bookingInfo, [key]: next } }));
  const updateRequirements = (key: keyof Opportunity["requirements"], next: string | boolean) => setVenue((current) => ({ ...current, requirements: { ...current.requirements, [key]: next } }));
  const updateMatching = (key: keyof Opportunity["matching"], next: string | boolean) => setVenue((current) => ({ ...current, matching: { ...current.matching, [key]: next } }));

  const addGallery = async (files: FileList | null) => {
    if (!files) return;
    setGalleryError("");
    const remaining = Math.max(0, 8 - venue.publicInfo.gallery.length);
    const selected = [...files].slice(0, remaining);
    for (const file of selected) {
      if (!/^image\/(jpeg|png|webp)$/.test(file.type)) { setGalleryError("Gallery accepts JPG, JPEG, PNG, or WebP only."); continue; }
      if (file.size > 10 * 1024 * 1024) { setGalleryError("Each gallery image must be 10 MB or smaller."); continue; }
      const data = await fileToDataUrl(file);
      setVenue((current) => ({ ...current, publicInfo: { ...current.publicInfo, gallery: [...current.publicInfo.gallery, data].slice(0, 8) } }));
    }
  };

  const submit = (event: React.FormEvent) => { event.preventDefault(); onSave(normalizeOpportunity({ ...venue, id: venue.id || slugify(venue.publicInfo.venueName), opportunityTitle: venue.opportunityTitle || "Booking opportunity", date: venue.date || "Dates available", matchScore: Math.max(1, Math.min(99, venue.matchScore || 75)) })); };

  return <form className="gg-venue-form" onSubmit={submit}><div className="gg-form-top"><button type="button" onClick={onCancel}><ArrowLeft size={15}/> Manage Venues</button><div><span className="gg-kicker">Venue editor</span><h1>{value.publicInfo.venueName ? `Edit ${value.publicInfo.venueName}` : "Add Venue"}</h1></div><button type="submit" className="primary">Save venue</button></div>
    <FormSection title="Basic info"><Field label="Venue name" value={venue.publicInfo.venueName} required onChange={(v) => updatePublic("venueName", v)}/><Field label="Venue type" value={venue.publicInfo.venueType} onChange={(v) => updatePublic("venueType", v)}/><Field label="Address" value={venue.publicInfo.address} onChange={(v) => updatePublic("address", v)}/><Field label="City" value={venue.publicInfo.city} onChange={(v) => updatePublic("city", v)}/><Field label="State" value={venue.publicInfo.state} onChange={(v) => updatePublic("state", v)}/><Field label="ZIP" value={venue.publicInfo.zip} onChange={(v) => updatePublic("zip", v)}/><Field label="Country" value={venue.publicInfo.country} onChange={(v) => updatePublic("country", v)}/><Field label="Capacity" value={venue.publicInfo.capacity} onChange={(v) => updatePublic("capacity", v)}/><Field label="Opportunity / gig" value={venue.opportunityTitle} onChange={(v) => setVenue({ ...venue, opportunityTitle: v })}/><Field label="Date" value={venue.date} onChange={(v) => setVenue({ ...venue, date: v })}/><Field label="Match %" value={String(venue.matchScore)} type="number" onChange={(v) => setVenue({ ...venue, matchScore: Number(v) })}/><Field wide label="Description" value={venue.publicInfo.description} multiline onChange={(v) => updatePublic("description", v)}/></FormSection>
    <FormSection title="Matching"><Field label="Genres" value={venue.matching.genres} onChange={(v) => updateMatching("genres", v)}/><Field label="Typical artists" value={venue.matching.typicalArtists} onChange={(v) => updateMatching("typicalArtists", v)}/><Field label="Venue vibe" value={venue.matching.venueVibe} onChange={(v) => updateMatching("venueVibe", v)}/><Field label="Minimum capacity" value={venue.matching.minimumCapacity} onChange={(v) => updateMatching("minimumCapacity", v)}/><Field label="Maximum capacity" value={venue.matching.maximumCapacity} onChange={(v) => updateMatching("maximumCapacity", v)}/><Field wide label="Why it matches" value={venue.matching.whyItMatches} multiline onChange={(v) => updateMatching("whyItMatches", v)}/><Check label="Emerging artists accepted" checked={venue.matching.emergingArtistsAccepted} onChange={(v) => updateMatching("emergingArtistsAccepted", v)}/><Check label="Support slots available" checked={venue.matching.supportSlotsAvailable} onChange={(v) => updateMatching("supportSlotsAvailable", v)}/></FormSection>
    <FormSection title="Contact"><Field label="Public website" value={venue.publicInfo.website} type="url" onChange={(v) => updatePublic("website", v)}/><Field label="Public Instagram" value={venue.publicInfo.instagram} onChange={(v) => updatePublic("instagram", v)}/><Field label="Public phone" value={venue.publicInfo.publicPhone} onChange={(v) => updatePublic("publicPhone", v)}/><Field label="Booking page" value={venue.publicInfo.bookingPage} type="url" onChange={(v) => updatePublic("bookingPage", v)}/></FormSection>
    <FormSection title="Private booking contact" note="Visible only to authenticated artists."><Field label="Booking contact name" value={venue.bookingInfo.contactName} onChange={(v) => updateBooking("contactName", v)}/><Field label="Booking email" value={venue.bookingInfo.email} type="email" onChange={(v) => updateBooking("email", v)}/><Field label="Booking phone" value={venue.bookingInfo.phone} onChange={(v) => updateBooking("phone", v)}/><Field label="Preferred contact method" value={venue.bookingInfo.preferredContactMethod} onChange={(v) => updateBooking("preferredContactMethod", v)}/><Field label="Submission link" value={venue.bookingInfo.submissionLink} type="url" onChange={(v) => updateBooking("submissionLink", v)}/><Field wide label="Booking instructions" value={venue.bookingInfo.bookingInstructions} multiline onChange={(v) => updateBooking("bookingInstructions", v)}/><Field wide label="Internal notes" value={venue.bookingInfo.internalNotes} multiline onChange={(v) => updateBooking("internalNotes", v)}/></FormSection>
    <FormSection title="Photos" note="Use clear, high-quality images. Avoid screenshots or heavily compressed photos."><div className="gg-form-wide"><ImageUploader label="Cover photo" value={venue.publicInfo.coverImage} maxMb={10} minimum={{ width: 1600, height: 900 }} recommendation="16:9 landscape recommended" onChange={(v) => updatePublic("coverImage", v)}/></div><div className="gg-form-wide gg-gallery-editor"><strong>Gallery</strong><p>JPG, JPEG, PNG, WebP · maximum 8 images · 10 MB each · minimum 1200 px width recommended</p><div>{venue.publicInfo.gallery.map((src, index) => <button key={index} type="button" onClick={() => setVenue((current) => ({ ...current, publicInfo: { ...current.publicInfo, gallery: current.publicInfo.gallery.filter((_, i) => i !== index) } }))}><SafeImage src={src} alt={`Gallery ${index + 1}`}/><span>Remove</span></button>)}</div><input ref={galleryRef} hidden multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => void addGallery(e.target.files)}/><button type="button" className="gg-add-gallery" onClick={() => galleryRef.current?.click()} disabled={venue.publicInfo.gallery.length >= 8}><ImagePlus size={15}/> Add gallery photos</button>{galleryError && <p className="gg-field-error">{galleryError}</p>}</div></FormSection>
    <FormSection title="Booking requirements"><Field label="Genres" value={venue.requirements.genrePreferences} onChange={(v) => updateRequirements("genrePreferences", v)}/><Field label="Set length" value={venue.requirements.typicalSetLength} onChange={(v) => updateRequirements("typicalSetLength", v)}/><Field label="Draw requirement" value={venue.requirements.drawRequirement} onChange={(v) => updateRequirements("drawRequirement", v)}/><Field label="Minimum audience" value={venue.requirements.minimumAudience} onChange={(v) => updateRequirements("minimumAudience", v)}/><Field label="Payment model" value={venue.requirements.paymentModel} onChange={(v) => updateRequirements("paymentModel", v)}/><Field label="Typical guarantee" value={venue.requirements.typicalGuarantee} onChange={(v) => updateRequirements("typicalGuarantee", v)}/><Field label="Door split" value={venue.requirements.doorSplit} onChange={(v) => updateRequirements("doorSplit", v)}/><Field label="Age restriction" value={venue.requirements.ageRequirement} onChange={(v) => updateRequirements("ageRequirement", v)}/><Field wide label="Required materials" value={venue.requirements.requiredMaterials} multiline onChange={(v) => updateRequirements("requiredMaterials", v)}/><Field wide label="Equipment / backline" value={venue.requirements.equipment} multiline onChange={(v) => updateRequirements("equipment", v)}/><Field wide label="Other requirements" value={venue.requirements.otherRequirements} multiline onChange={(v) => updateRequirements("otherRequirements", v)}/><Check label="EPK required" checked={venue.requirements.epkRequired} onChange={(v) => updateRequirements("epkRequired", v)}/><Check label="Music links required" checked={venue.requirements.musicLinksRequired} onChange={(v) => updateRequirements("musicLinksRequired", v)}/><Check label="Social links required" checked={venue.requirements.socialLinksRequired} onChange={(v) => updateRequirements("socialLinksRequired", v)}/></FormSection>
    <FormSection title="Data quality"><Field label="Source URL" value={venue.dataQuality.sourceUrl} type="url" onChange={(v) => setVenue({ ...venue, dataQuality: { ...venue.dataQuality, sourceUrl: v } })}/><Field label="Last verified date" value={venue.dataQuality.lastVerifiedDate} type="date" onChange={(v) => setVenue({ ...venue, dataQuality: { ...venue.dataQuality, lastVerifiedDate: v } })}/><label className="gg-field"><span>Verification status</span><select value={venue.dataQuality.verificationStatus} onChange={(e) => setVenue({ ...venue, dataQuality: { ...venue.dataQuality, verificationStatus: e.target.value as VerificationStatus } })}><option>Unverified</option><option>Verified</option><option>Needs review</option></select></label><Check label="Sample / demo venue" checked={venue.dataQuality.isDemo} onChange={(v) => setVenue({ ...venue, dataQuality: { ...venue.dataQuality, isDemo: v } })}/></FormSection>
    <div className="gg-form-submit"><button type="button" onClick={onCancel}>Cancel</button><button type="submit" className="primary">Save venue</button></div>
  </form>;
}

function FormSection({ title, note, children }: { title: string; note?: string; children: React.ReactNode }) { return <section className="gg-form-section"><header><h2>{title}</h2>{note && <p>{note}</p>}</header><div className="gg-form-grid">{children}</div></section>; }
function Field({ label, value, onChange, multiline, wide, required, type = "text" }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean; wide?: boolean; required?: boolean; type?: string }) { return <label className={`gg-field ${wide ? "gg-form-wide" : ""}`}><span>{label}</span>{multiline ? <textarea value={value} required={required} onChange={(e) => onChange(e.target.value)}/> : <input value={value} required={required} type={type} onChange={(e) => onChange(e.target.value)}/>}</label>; }
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="gg-check"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)}/><span>{label}</span></label>; }
function fileToDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); }
function slugify(value: string) { return `${value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "venue"}-${Date.now()}`; }
function blankVenue(): Opportunity { return { id: "", venueName: "", opportunityTitle: "", city: "", state: "", date: "", genre: "", compensationSummary: "", expectedDraw: "", matchScore: 75, image: "", description: "", coordinate: [42.3601, -71.0589], publicInfo: { venueName: "", venueType: "", address: "", city: "", state: "", zip: "", country: "United States", capacity: "", description: "", website: "", instagram: "", publicPhone: "", bookingPage: "", coverImage: "", gallery: [] }, bookingInfo: { contactName: "", email: "", phone: "", preferredContactMethod: "Email", bookingInstructions: "", submissionLink: "", internalNotes: "" }, requirements: { genrePreferences: "", typicalSetLength: "", ageRequirement: "", drawRequirement: "", minimumAudience: "", paymentModel: "", typicalGuarantee: "", doorSplit: "", ticketRequirements: "", equipment: "", requiredMaterials: "", epkRequired: false, musicLinksRequired: false, socialLinksRequired: false, otherRequirements: "" }, matching: { genres: "", typicalArtists: "", venueVibe: "", minimumCapacity: "", maximumCapacity: "", emergingArtistsAccepted: true, supportSlotsAvailable: false, whyItMatches: "" }, dataQuality: { sourceUrl: "", lastVerifiedDate: "", verificationStatus: "Unverified", isDemo: false } }; }
